// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in UglyOps user's ID and email as seen by the MCP server.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-employees.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !anon) throw new Error("Supabase URL / publishable key not configured");
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-employees.ts
var list_employees_default = defineTool2({
  name: "list_employees",
  title: "List employees",
  description: "List employees visible to the signed-in user. Tenant isolation, manager scoping, and role permissions are enforced by the database via RLS.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).default(50).describe("Max rows to return."),
    search: z.string().optional().describe("Case-insensitive match on first or last name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("employees").select("id, first_name, last_name, email, employee_status, branch_id, role").limit(limit);
    if (search) {
      q = q.or(`first_name.ilike.%${search}%,last_name.ilike.%${search}%`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { employees: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-employee.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_employee_default = defineTool3({
  name: "get_employee",
  title: "Get employee",
  description: "Return a single employee record by id. RLS enforces tenant, branch, and role visibility.",
  inputSchema: {
    employee_id: z2.string().uuid().describe("Employee UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ employee_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("employees").select(
      "id, first_name, last_name, email, employee_status, branch_id, role, employment_start_date, employment_end_date"
    ).eq("id", employee_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "Employee not found or not visible to this user" }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { employee: data }
    };
  }
});

// src/lib/mcp/tools/list-holiday-requests.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_holiday_requests_default = defineTool4({
  name: "list_holiday_requests",
  title: "List holiday requests",
  description: "List holiday requests visible to the signed-in user. Staff see their own; managers/admins see requests in scope. RLS enforces the boundary.",
  inputSchema: {
    status: z3.enum(["pending", "approved", "rejected", "cancelled"]).optional().describe("Filter by request status."),
    limit: z3.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("holiday_requests").select("id, employee_id, start_date, end_date, status, hours, request_type, created_at").order("start_date", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { holiday_requests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-payroll-periods.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_payroll_periods_default = defineTool5({
  name: "list_payroll_periods",
  title: "List payroll periods",
  description: "List payroll periods visible to the signed-in user. Read-only. RLS restricts to the user's tenant; typically only admins see rows.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("payroll_periods").select("id, period_start, period_end, pay_date, status, name").order("period_start", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { payroll_periods: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hukujeeeawfuywpiclyd";
var mcp_default = defineMcp({
  name: "uglyops-mcp",
  title: "UglyOps",
  version: "0.1.0",
  instructions: "Read-only tools for UglyOps: employees, holiday requests, and payroll periods. All access is scoped to the signed-in user by row-level security (tenant, branch, and role).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_employees_default, get_employee_default, list_holiday_requests_default, list_payroll_periods_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
